FROM rosatrancoso/base

RUN echo "Installing mpich..." &&\
    cd /tmp &&\
    wget http://www.mpich.org/static/downloads/3.2/mpich-3.2.tar.gz &&\
    tar zxvf mpich-3.2.tar.gz &&\
    cd mpich-3.2 &&\
    ./configure 2>&1 | tee configure.log &&\
    make 2>&1 | tee make.log &&\
    make check 2>&1 | tee make_check.log &&\
    sudo make install 2>&1 | tee make_install.log &&\
    cd ../



# do this outside because too slow
# RUN git clone --depth 1 https://github.com/wrf-model/WRF $REPOS/wrf &&\
#     cd $REPOS/wrf &&\
#     git fetch --tags &&\
#     latesttag=$(git describe --tags `git rev-list --tags --max-count=1`)
#     echo checking out ${latesttag}&&\
#     git checkout -b $latesttag $latesttag


# v5.0.2
# RUN git clone git@github.com:NCAR/wrf_hydro_nwm_public.git $REPOS/wrf-model/wrf_hydro_nwm_public &&\
#     cd $REPOS/wrf-model/wrf_hydro_nwm_public &&\
#     git fetch --tags &&\
#     latesttag=$(git describe --tags `git rev-list --tags --max-count=1`)
#     echo checking out ${latesttag}&&\
#     git checkout -b $latesttag $latesttag





