# export UID=`id -u`; export GID=`id -g`; docker-compose up -d wrfhydro_v5.2.0-rc2_noahmp_spatial_soil0

version: "3.3"

services:

  wrfhydro_v5.2.0-rc2_noahmp_spatial_soil0:
    build:
      context: .
      dockerfile: Dockerfile.wrfhydro_v5.2.0-rc2_NoahMP_SPATIAL_SOIL0
    tty: True
    user: $UID:$GID
    volumes:
      - $PWD/test_cases:/data/test_cases

  hysplit_local:
    build:
      context: .
      dockerfile: Dockerfile.hysplit
    tty: True
    user: $UID:$GID:$USER
    volumes:
      - $HOME/hysplit:/source/hysplit
      - $HOME/Documents/MS/Hysplit:$HOME/Documents/MS/Hysplit

  hysplit_wrapper:
    build:
      context: .
      dockerfile: Dockerfile.hysplit
    tty: True
    user: $UID:$GID:$USER
    volumes:
      - /tmp/hysplit:/tmp/hysplit
      - $REPOSMS/hysplit_wrapper:/source/hysplit_wrapper
      - $REPOSMS/config-hysplit:/source/config-hysplit
