# export UID=`id -u`; export GID=`id -g`; docker-compose up -d

version: "3.3"

services:

  mohid:
    build:
      context: .
      dockerfile: Dockerfile
    tty: True
    user: $UID:$GID:$USER
    volumes:
      - $MYREPOS/Mohid:/source/mohid
      - $HOME/scratch/wrf2hdf5:/tmp/wrf2hdf5

