# export UID=`id -u`; export GID=`id -g`; docker compose up -d wrfhydro_v5.2.0-rc2_noahmp_spatial_soil0


version: "3.3"

services:

  wrfhydro_v5.2.0-rc2_noahmp_spatial_soil0:
    build:
      context: .
      dockerfile: Dockerfile.wrfhydro_v5.2.0-rc2_NoahMP_SPATIAL_SOIL0
    tty: True
    user: $UID:$GID
    volumes:
      - $HOME/scratch/test_cases:/data/test_cases
      - $REPOSMS/wrfhydro_tools:/data/wrfhydro_tools

  wrfhydro_v5.2.0-rc2_noahmp_spatial_soil1:
    build:
      context: .
      dockerfile: Dockerfile.wrfhydro_v5.2.0-rc2_NoahMP_SPATIAL_SOIL1
    tty: True
    user: $UID:$GID
    volumes:
      - $HOME/scratch/test_cases:/data/test_cases
      - $REPOSMS/wrfhydro_tools:/data/wrfhydro_tools


# no daemon here 
# export UID=`id -u`; export GID=`id -g`; docker compose up wrfhydro_training

# Error retrieving test case so copy manually 
# cp /mnt/c/Users/rtrancoso/Downloads/croton_NY_training_example_v5.2.tar.gz ~/scratch/test_cases/
# change paths in lesson 2


  wrfhydro_training:
    image: wrfhydro/training:v5.2.0-rc1
    ports:
      - 8888:8888
    tty: true
    volumes:
      - $HOME/scratch:/home/docker/scratch
    environment:
     - JUPYTER_ENABLE_LAB=yes
     - NB_UID=$UID #$(id -u)
     - NB_GID=$GID #(id -g)
