FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt -y update &&\
    apt install -y \
    vim \
    git \
    libmpich-dev \
    libnetcdff-dev \
    netcdf-bin \
    make \
    wget

ENV REPOS="/source" WRFH_VERSION="5.2.0-rc2"
RUN mkdir $REPOS

RUN echo "------- Install WRF-Hydro -----" &&\
    cd /source &&\
    wget -q https://github.com/NCAR/wrf_hydro_nwm_public/archive/v$WRFH_VERSION.tar.gz &&\
    tar -zxf v$WRFH_VERSION.tar.gz &&\
    ln -s wrf_hydro_nwm_public-$WRFH_VERSION wrf_hydro_nwm_public &&\
    cd wrf_hydro_nwm_public/trunk/NDHMS &&\
    ./configure 2

RUN cd /source/wrf_hydro_nwm_public/trunk/NDHMS &&\
    echo "export WRF_HYDRO=1" > setEnvar.sh &&\
    echo "export HYDRO_D=1" >> setEnvar.sh &&\
    echo "export SPATIAL_SOIL=0" >> setEnvar.sh &&\
    echo "export WRF_HYDRO_RAPID=0" >> setEnvar.sh &&\
    echo "export NCEP_WCOSS=0" >> setEnvar.sh &&\
    echo "export NWM_META=0" >> setEnvar.sh &&\
    echo "export WRF_HYDRO_NUDGING=0" >> setEnvar.sh &&\
    #cp -f template/setEnvar.sh setEnvar.sh &&\
    ./compile_offline_NoahMP.sh setEnvar.sh

# RUN mkdir /data/run &&\
#     cd /data/run &&\

#      mkdir run_gridded_no_lakes
#      cd run_gridded_no_lakes
#      cp $REPOS/wrf_hydro_nwm_public/trunk/NDHMS/Run/*.TBL . &&\
#      cp $REPOS/wrf_hydro_nwm_public/trunk/NDHMS/Run/wrf_hydro.exe .
#      cp $REPOS/wrf_hydro_nwm_public/trunk/NDHMS/Run/*namelist*

#      mkdir DOMAIN
#      cd DOMAIN
#      unzip ../../../gis/output_Reporoa/Reporoa.zip -d .
#      ln -s ../../../taur0p5kmN_v2/geo_em.d04.nc .
#      ln -s ../../../taur0p5kmN_v2/wrfinput_d04 .

#      ln -s ../FORCING/

# mpirun -np 2 ./wrf_hydro.exe >> run.log 2>&1

# # cp /source/wrf_hydro_nwm_public/trunk/NDHMS/Run/namelist.hrldase
# docker exec -ti --user $(id -u):$(id -g) agritech_wrf-hydro_1 bash

#https://ral.ucar.edu/sites/default/files/public/create_wrfinput.zip
#https://ral.ucar.edu/sites/default/files/public/create_soilproperties.zip

