# export UID=`id -u`; export GID=`id -g`; docker compose up -d mywrfhydro
# docker-compose build --progress plain --no-cache mywrfhydro1 2>&1  |tee log

version: "3.3"

services:

  mywrfhydro:
    image: docker-scipy-notebook_scipy_gis
    tty: true
    user: root
    ports:
      - 8888:8888
    volumes:
      - $HOME/scratch:/home/jovyan/scratch
      - $REPOS/NCAR:/home/jovyan/NCAR
    environment:
     - JUPYTER_ENABLE_LAB=yes
     - NB_UID=$UID
     - NB_GID=$GID

  mywrfhydro1:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    user: root
    ports:
      - 8889:8888
    volumes:
      - $HOME/scratch:/home/jovyan/scratch
      - $REPOS/NCAR:/home/jovyan/NCAR
    environment:
     - JUPYTER_ENABLE_LAB=yes
     - NB_UID=$UID
     - NB_GID=$GID


# no daemon here 
# export UID=`id -u`; export GID=`id -g`; docker compose up wrfhydro_training

# Error retrieving test case so copy manually 
# cp /mnt/c/Users/rtrancoso/Downloads/croton_NY_training_example_v5.2.tar.gz ~/scratch/test_cases/
# change paths in lesson 2

  # doesnt work on SBH desktop and has old version of the model
  wrfhydro_training:
    image: wrfhydro/training:v5.2.0-rc1
    tty: true
    user: root
    ports:
      - 8888:8888
    volumes:
      - $HOME/scratch:/home/docker/scratch
    environment:
     - JUPYTER_ENABLE_LAB=yes
     - NB_UID=$UID
     - NB_GID=$GID

