# export UID=`id -u`; export GID=`id -g`; docker-compose up -d



taur:
  image: wrfhydro/training:v5.2.0-rc1
  ports:
    - 8889:8888
  tty: true
  volumes:
    - $PWD:/home/docker/taur0p5kmN_v2/
#  environment:
#    - JUPYTER_ENABLE_LAB=yes
#    - NB_UID=$UID #$(id -u)
#    - NB_GID=$GID #(id -g)
